name: Publish to AWS SNS Topic

on:
  push:
    branches:
      - main

jobs:
  publish-to-sns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Publish to SNS
        run: |
          aws sns publish --topic-arn ${{ secrets.SNS_TOPIC_ARN }} --message "Hello from GitHub Actions!"
